# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dacf5fc0fd5f8b0a79a3eaad974409ee76efd2becfca39ded50cf85894e1e103d2c1181ec1e11dfd85d360ee421e26a1f7e8cc4f907ef4b68925ae81d6ae7fb4

test:
  secret_key_base: b601fa93ff84ecdb496361540e4723203b418a0fed11fb6252135d236fafae128df7a67312b59162df92e3a30399d829089c7aefa3c2c97b0e54cae2f502c9fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
